docs: submodule 적용기 작성
jujeol-jujeol/jujeol-jujeol.github.io pull request #3
Opened 2021-07-13 23:57 UTC by sihyung92

2021-07-14 04:16 UTC, sunhpark42 requested changes
글 잘 읽었습니다~~ 저희 팀의 깃허브 서브 모듈이 이렇게 적용 된 거군요! 굿굿 👍👍

2021-07-14 04:16 UTC, sunhpark42 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +   ├── fronend
fronend 오타있어용~~

2021-07-14 04:18 UTC, sunhpark42 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +tags: [git]
그리고 이 태그 카테고리 같은 기능이라서 jojal-jojal 로 바꿔 주셔야 할 것 같아용~

2021-07-14 04:23 UTC, sihyung92 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +   ├── fronend
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-07-14 04:23 UTC, sihyung92 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +tags: [git]
아하!! 알게씁니다

2021-07-14 04:28 UTC, sunhpark42 commented on _data/authors.yml
> +  github: <sihyung92>
이것도 \<> 이거 빼고 작성해 주셔야, 깃허브 아이콘 눌렀을 때 정상적으로 갑니당

2021-07-14 04:37 UTC, sihyung92 commented on _data/authors.yml
> +  github: <sihyung92>
조와요 조와요

2021-07-14 04:45 UTC, sunhpark42 approved these changes
수정확인했습니당!

2021-07-15 01:20 UTC, devhyun637 commented
진짜 짱이야 감자 서브모듈👍👍👍👍👍

2021-07-15 01:27 UTC, devhyun637 reviewed
아 근데 나도 글쓰면서 느끼는건데 우리가 헤맸다!! 근데 해결했어! 이런거 남기고 싶은데 그게 힘든거 같아.
그 백엔드가 하면서 어떻게 노력해서 만든건지 담긴 그런 고생스러움이 풀풀 나는 글도 나중엔 좋을듯!!

이거 다른 사람들이 보면서 엄청 도움될거같아서 조아욘 감자 짱👍👍👍👍

2021-07-15 01:27 UTC, devhyun637 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +   ```
이거 간지

2021-07-15 01:27 UTC, devhyun637 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +
물결표 지워달라하면 혼나나요?

2021-07-15 01:52 UTC, sihyung92 commented on _posts/2021-07-12-git-submodule-적용하기.md
> +
ㅠ 물결압수

2021-07-15 04:16 UTC, merged